// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xglwniepemchvtmmtzwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhnbHduaWVwZW1jaHZ0bW10endyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NjkxMjksImV4cCI6MjA2NTE0NTEyOX0.RNrbDOEUoodX6Edn2Zv_YwvEph8ViF9TBRwRqWqrgUk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);